version: '3.8'

services:
  # AI Career Coach API Backend
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - HOST=0.0.0.0
      - PORT=9000
      - LOG_LEVEL=INFO
    env_file:
      - ./api/.env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - career-coach-network

  # Frontend Next.js Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://api:9000
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - career-coach-network

networks:
  career-coach-network:
    driver: bridge